In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_mordred = pd.read_csv("result/mordred_25286.csv")
data_RDKit = pd.read_csv("result/rdkit_25286.csv")

print(data_mordred.head())
print(data_RDKit.head())

         ABC      ABCGG  nAcid  nBase    SpAbs_A   SpMax_A  SpDiam_A  \
0  14.170645  12.800886    0.0    0.0  24.746903  2.322363  4.644727
1  12.344244  11.318664    1.0    0.0  19.975571  2.493097  4.859563
2  16.539255  14.283122    0.0    0.0  27.349206  2.414274  4.828548
3  14.946702  13.146952    0.0    0.0  25.658513  2.376715  4.753430
4  20.164156  15.981222    0.0    1.0  32.652758  2.783989  5.365780

      SpAD_A   SpMAD_A   LogEE_A  ...      SRW10     TSRW10          MW  \
0  24.746903  1.237345  3.865710  ...   9.523763  52.517660  277.167794
1  19.975571  1.248473  3.705531  ...   9.805047  63.114996  218.057909
2  27.349206  1.243146  3.997485  ...   9.962087  55.953673  303.169525
3  25.658513  1.282926  3.896709  ...   9.656499  52.964882  289.077264
4  32.652758  1.360532  4.204742  ...  10.947098  77.909098  326.199428

        AMW   WPath  WPol  Zagreb1  Zagreb2  mZagreb1  mZagreb2
0  6.445763   915.0  28.0     90.0    101.0  8.055556  4.972222
1  8.386843   412.0  25.0     84.0    100.0  6.256944  3.486111
2  7.050454  1065.0  35.0    110.0    128.0  8.888889  5.027778
3  8.259350   797.0  28.0     96.0    109.0  6.555556  4.666667
4  6.523989  1033.0  60.0    156.0    211.0  7.145833  4.958333

[5 rows x 1613 columns]
       Substance ID                                             SMILES  \
0  ZINC000000000007                   C=CCc1ccc(OCC(=O)N(CC)CC)c(OC)c1
1  ZINC000000000010                  C[C@@]1(c2ccccc2)OC(C(=O)O)=CC1=O
2  ZINC000000000011                 COc1cc(Cc2cnc(N)nc2N)cc(OC)c1N(C)C
3  ZINC000000000012               O=C(C[S@@](=O)C(c1ccccc1)c1ccccc1)NO
4  ZINC000000000014  CC[C@H]1[C@H](O)N2[C@H]3C[C@@]45c6ccccc6N(C)[C...

      BertzCT    Kappa3
0  453.035249  4.296921
1  475.051945  1.480754
2  647.972650  3.133457
3  547.082326  3.525005
4  723.345329  1.204324

In [3]:
ABCGG = pd.DataFrame(data_mordred['ABCGG'], columns=['ABCGG'])

In [4]:
task_25286 = pd.concat([data_RDKit, ABCGG], axis=1, join='inner')
task_25286 = task_25286.drop(['Substance ID'], axis=1)
task_25286

,SMILES,BertzCT,Kappa3,ABCGG
0,C=CCc1ccc(OCC(=O)N(CC)CC)c(OC)c1,453.035249,4.296921,12.800886
1,C[C@@]1(c2ccccc2)OC(C(=O)O)=CC1=O,475.051945,1.480754,11.318664
2,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1N(C)C,647.972650,3.133457,14.283122
3,O=C(C[S@@](=O)C(c1ccccc1)c1ccccc1)NO,547.082326,3.525005,13.146952
4,CC[C@H]1[C@H](O)N2[C@H]3C[C@@]45c6ccccc6N(C)[C...,723.345329,1.204324,15.981222
...,...,...,...,...
25281,CC(C)COC(=O)Oc1c(Cl)cc2oc(=O)sc2c1[N+](=O)[O-],794.604059,3.366089,14.971375
25282,Cc1c(C(=O)NN=C2CCCC2)nnn1-c1nonc1N,692.896724,2.465916,14.861267
25283,CN(C)c1nc2nonc2nc1Nc1cccc(Cl)c1,756.542291,2.348616,13.281137
25284,COc1cccc(NC(=O)CSC(N)=O)c1,395.405461,4.222977,10.370706
25285,O=C1c2cccc([N+](=O)[O-])c2C(=O)N1CCOc1ccccc1,788.312534,2.637007,14.674016

In [5]:
for i in ['ABCGG', 'Kappa3', 'BertzCT']:
    task_25286 = task_25286[pd.to_numeric(task_25286[i], errors='coerce').notnull()]

task_25286.to_csv('result/data_25286.csv', index=False)

task_25286

,SMILES,BertzCT,Kappa3,ABCGG
0,C=CCc1ccc(OCC(=O)N(CC)CC)c(OC)c1,453.035249,4.296921,12.800886
1,C[C@@]1(c2ccccc2)OC(C(=O)O)=CC1=O,475.051945,1.480754,11.318664
2,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1N(C)C,647.972650,3.133457,14.283122
3,O=C(C[S@@](=O)C(c1ccccc1)c1ccccc1)NO,547.082326,3.525005,13.146952
4,CC[C@H]1[C@H](O)N2[C@H]3C[C@@]45c6ccccc6N(C)[C...,723.345329,1.204324,15.981222
...,...,...,...,...
25281,CC(C)COC(=O)Oc1c(Cl)cc2oc(=O)sc2c1[N+](=O)[O-],794.604059,3.366089,14.971375
25282,Cc1c(C(=O)NN=C2CCCC2)nnn1-c1nonc1N,692.896724,2.465916,14.861267
25283,CN(C)c1nc2nonc2nc1Nc1cccc(Cl)c1,756.542291,2.348616,13.281137
25284,COc1cccc(NC(=O)CSC(N)=O)c1,395.405461,4.222977,10.370706
25285,O=C1c2cccc([N+](=O)[O-])c2C(=O)N1CCOc1ccccc1,788.312534,2.637007,14.674016