In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

In [2]:
def calculate_statistics(group):
    r2_test = group['r2_test']
    r2_test_dict = {f'run{i}': r2_test_val for i, r2_test_val in enumerate(r2_test)}
    return pd.Series({
        **r2_test_dict, 
        'r2_test_mean': np.mean(r2_test),
        'r2_test_max': np.max(r2_test),
        'r2_test_min': np.min(r2_test),
        'r2_test_std': np.std(r2_test, ddof=0),
    })

def calculate_statistics2(group):
    rmse_test = group['rmse_test']
    rmse_test_dict = {f'run{i}': rmse_test_val for i, rmse_test_val in enumerate(rmse_test)}
    return pd.Series({
        **rmse_test_dict, 
        'rmse_test_mean': np.mean(rmse_test),
        'rmse_test_max': np.max(rmse_test),
        'rmse_test_min': np.min(rmse_test),
        'rmse_test_std': np.std(rmse_test, ddof=0),
    })

In [3]:
results_r2 = []
results_rmse = []
for i in range(10):
    for dataset in ['RDKit', 'mordred']:
        data = pd.read_csv(f'data/data_{dataset}.csv')
        y = pd.DataFrame(data['Yield'],columns=['Yield'])
        X = data.drop(columns=['Name', 'ID', 'Yield'])
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=i)
        param = {"n_estimators": [100, 1000, 5000], "max_depth": [3, 4, 5, 6]}
        reg = GridSearchCV(RandomForestRegressor(random_state=0), param_grid=param, cv=10, n_jobs=4)
        reg.fit(X_train,y_train['Yield'])
        best = reg.best_estimator_
        y_pred1 = best.predict(X_train)
        y_pred2 = best.predict(X_test)
        r2_test_score = metrics.r2_score(y_test, y_pred2)
        rmse_test_score = metrics.root_mean_squared_error(y_test, y_pred2)
        results_r2.append({'desc': dataset,'r2_test': r2_test_score})
        results_rmse.append({'desc': dataset, 'rmse_test': rmse_test_score})

results_df = pd.DataFrame(results_r2)
gen_results = results_df.groupby(['desc']).apply(calculate_statistics).reset_index()
results_df2 = pd.DataFrame(results_rmse)
gen_results2 = results_df2.groupby(['desc']).apply(calculate_statistics2).reset_index()

In [4]:
gen_results.T.to_csv('result/result_r2.csv', header=False)
gen_results.T

                     0         1
desc             RDKit   mordred
run0         -0.423975 -0.469664
run1          0.384212  0.255927
run2          0.204394   0.31599
run3          0.158322  0.210935
run4          0.212564  0.163386
run5          0.271894  0.376069
run6          0.082285  0.192457
run7          0.249867  0.187115
run8          0.142945  0.107254
run9          0.199497  0.178111
r2_test_mean    0.1482  0.151758
r2_test_max   0.384212  0.376069
r2_test_min  -0.423975 -0.469664
r2_test_std   0.205701  0.219892

In [5]:
gen_results2.T.to_csv('result/result_rmse.csv', header=False)
gen_results2.T

                        0          1
desc                RDKit    mordred
run0            26.519979  26.942077
run1            17.453906  19.186008
run2            23.292404  21.597152
run3            22.828902   22.10388
run4             23.19424  23.907548
run5             23.02028  21.309901
run6            23.450179  21.997586
run7            23.396458  24.355426
run8            23.698403  24.186804
run9             21.32959  21.612624
rmse_test_mean  22.818434  22.719901
rmse_test_max   26.519979  26.942077
rmse_test_min   17.453906  19.186008
rmse_test_std    2.158947   2.047642